sudo: false

language: node_js

os:
  - linux
  - osx

node_js:
  - 6
  - 4

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

script:
  - node --version
  - npm --version
  - npm run test

notifications:
  email: false
