sudo: false

language: node_js

os:
  - linux
  - osx

node_js:
  - 7
  - 6
  - 4

cache: yarn

script:
  - node --version
  - yarn --version
  - yarn test

notifications:
  email: false

matrix:
  allow_failures:
    - node: 4
