sudo: false

language: node_js

os:
  - linux
  - osx

node_js:
  - 6
  - 4

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

before_install:
  - time npm i -g yarn --cache-min 999999999

install:
  - time yarn

script:
  - node --version
  - npm --version
  - npm run test

notifications:
  email: false
